### ISSUE TITLE
Private lobbies are unable to be joined by other users

### ISSUE THREAD

**Issue by miguemely** [Impostor/Impostor#206] opened 2020-12-04 14:33 UTC
# Bug Report

## Base Information
- Operating System: Debian 10
- Impostor Version: Impostor-Server_1.2.2-ci.121_linux-x64
- Among Us Version: v2020.11.17s

## I confirm:
- [X] that I have searched for an existing bug report for this issue.

## Symptoms 

Attempts to join a private lobby fail. See https://discordapp.com/channels/757425025379729459/760921187781312533/784424728050925620 for more details.

## Reproduction
Deploy server. Create private lobby. Join with another client.

**Comment by AeonLucid** [comment] 2020-12-10 01:30
Please copy the relevant information into the GitHub issue.

**Comment by XtraCube** [comment] 2021-02-08 01:54
I believe this issue is caused if your server is running on a port other than 22023. It happens because of how Among Us game code handles private game joining. When you use private codes, it always uses port 22023. There was a discussion about this in the Discord server for Impostor. The developer of Among Us said that it will be fixed in a future update

**Comment by encure** [comment] 2021-02-24 13:00
Hi,
i experienced the same issue, tried to deploy a multi node server setup (master + one node). This config seems to work for me right now (single node setup):

{
  "Server": {
    "PublicIp": "1.1.1.1",
    "PublicPort": 22023,
    "ListenIp": "0.0.0.0",
    "ListenPort": 22023,
    "Name": "impostor.example.net",
  },
  "ServerRedirector": {
    "Enabled": false,
    "Master": true,
    "Locator": {
      "Redis": "127.0.0.1.6379",
      "UdpMasterEndpoint": "127.0.0.1:22023"
    },
  }
}

only port 22023/udp is exposed.

**Comment by js6pak** [comment] 2021-03-03 09:44
Its a Among Us bug, private lobbies port is hardcoded to 22023 and from discrod messages it seems like they are using `6666`, iirc forte confirmed its going to be fixed in next update.

**Closed by js6pak** 2021-03-03 09:44 UTC
