### ISSUE TITLE
Epic and Steam Cross Play issue with 1.7 dev and 11.9

### ISSUE THREAD

**Issue by GD825** [Impostor/Impostor#443] opened 2021-12-03 01:51 UTC
# Bug Report

## Base Information
- Operating System - win 10
- Impostor Version - 1.7 (dev)
- Among Us Version - 11.9

## I confirm:
- [X] that I have searched for an existing bug report for this issue.

## Symptoms 

it appears players with the epic  games version have an issue where they cant join a host's game who has the steam version, but if they host it on their epic version, the steam player can  join them

players unable to join each other based on what version they have

have steam player make lobby and have epic games player try to join the lobby and vice versa

**Comment by AeonLucid** [comment] 2021-12-03 03:13
Related https://github.com/Impostor/Impostor/pull/442/files

**Comment by miniduikboot** [comment] 2022-01-09 20:56
Can't reproduce, probably related to oversized packets in 11.9. Closing until it can be repeated

**Closed by miniduikboot** 2022-01-09 20:56 UTC
