### ISSUE TITLE
amongus url scheme and Mobile support

### ISSUE THREAD

**Issue by MapleEve** [Impostor/Impostor#478] opened 2022-05-11 06:51 UTC
# Bug Report

## Base Information
- iOS
- 22.3.29s

## I confirm:
amongus url scheme cannot be used to connect to private server

## Symptoms 

init?servername=NAS&serverport=22023&serverip=36.24.xx.xx&usedtls=false

There's no more new servername in the bottom right of iOS app.

**Comment by miniduikboot** [comment] 2022-05-11 06:56
Hmm, I noticed it was a bit flaky on my side as well, but it did work in the end. Can you try closing down Among Us completely, then clicking the "Open in Among Us" button?

**Comment by MapleEve** [comment] 2022-05-11 08:27
> Hmm, I noticed it was a bit flaky on my side as well, but it did work in the end. Can you try closing down Among Us completely, then clicking the "Open in Among Us" button?

Ohh, when the Among Us running in background, it works.

But when I swipe and kill AU, and use the scheme to open a new instanse, it will not work.

**Comment by danbudworthmead** [comment] 2022-05-11 09:14
> > Hmm, I noticed it was a bit flaky on my side as well, but it did work in the end. Can you try closing down Among Us completely, then clicking the "Open in Among Us" button?
> 
> Ohh, when the Among Us running in background, it works.
> 
> But when I swipe and kill AU, and use the scheme to open a new instanse, it will not work.

Yeah because among us has to be running in the background for the deeplink to work. It's the way Innersloth added it.

**Comment by miniduikboot** [comment] 2023-07-07 14:19
Hey there, this issue has been open for a while and I think the issue is solved, so I'm closing this issue

**Closed by miniduikboot** 2023-07-07 14:19 UTC
